### ISSUE TITLE
Trim down the multi-module project into something of a more manageable size, refactor silliness.

### ISSUE THREAD

**Issue by kutis96** [CodeComesfromSpace/spacedoc#41]
### Rationale

The current multi-module setup is rather cute, however, moderately pointless.

Many modules could be merged into one, as they are likely to be used together anyway.

- `spacedoc-common`
  - likely to be used by all the things, according to the name
  - has a few utilities and somewhat common types, but not quite all of them
- `spacedoc-cdi`
  - slightly silly name
  - is probably the actually most commonly used component alongside config
- `spacedoc-config`
  - actually used by almost everything
  - _extremely_ heavy, there definitely is some room to trim some excess code here
- `spacedoc-ffc`
  - Probably good, do keep split off
  - A rename would make sense, perhaps to `spacedoc-external-renderers`?
- `spacedoc-markdown`
  - Do keep split off
- spacedoc-executable
  - It is robably smart to keep split off for more modular builds in the future.
  - Somehow contains MarkdownModule and LanguageRendererModule. Those should be moved to spacedoc-markdown and spacedoc-ffc respectively.

### Tasks
- [ ] Merge `spacedoc-common`, `spacedoc-cdi`, `spacedoc-config` into `spacedoc-common`
- [ ] Move MarkdownModule and LanguageRendererModule into `spacedoc-markdown` and `spacedoc-ffc`
- [ ] Rename spacedoc-ffc to something more sensible
- [ ] Rename all groupIds to `in.spcct.spacedoc`
- [ ] Rename all artifactIds, removing the `spacedoc-` prefix
